name: Setup Node

description: "Setup a Node.js environment for use in actions by"

inputs:
  version:
    description: "The version of Node.js to use"
    required: true
    default: "18"

runs:
  using: "composite"
  steps:
    - # setup node
      name: Setup Node.js ${{ inputs.version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.version }}
    - # Update npm
      name: Update npm
      shell: sh
      run: npm install -g npm@latest
    - # Install dependencies
      name: Install dependencies
      shell: sh
      run: npm install