name: Deployer
run-name: Deployer ${{ inputs.environment }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to ${{ vars.MESSAGE  }}"
